### ISSUE TITLE
Standardized classes for inter-vendor data structures

### ISSUE THREAD

**Issue by Mierdin** [jedelman8/cpal#1]
Jason, I'm wondering if we should build some additional classes for data types that are specific to networking devices, yet applicable to all vendor implementations. For instance - all routers have a routing table, but are represented in different ways.

It might be valuable to build out a class for this and other things like it. Each vendor module (cisco, junos, etc) is responsible for translating that vendor's specific representation of that data, and instantiating/populating the relevant class(es), and placing them into an array within each device instance.

For instance, I built this as an example into Cisco's NXAPI repo:
https://github.com/Mierdin/nexus9000/blob/master/examples/RoutingTable.py

If you think that's a good direction, we can build files for classes like these into a dedicated folder within the cpal repo.

Thoughts?

**Comment by jedelman8** [comment]
I know exactly what you are saying.  My initial intent was to have it loosely structured.  For example, you see functions in CPAL.py such as getCPU(), etc. that basically call getCPU in the per-vendor class.  This way as long as each module has a getCPU() method, we are all good - the goal wasn't to dictate anything that was going on in the vendor's module.  And the direction was keep it simple with strings, lists, and dictionaries! The data types in onePK are just messy.

But now you have me thinking twice.  I wonder if having structure around these data types (like routing tables) is the right amount of structure or too much structure.  As I write this, I realize I created the onePK and the Arista class and I was unknowingly doing the same thing already, but without the class structure per se.  Maybe we go with it?  I'm on the fence...any more thoughts on your end after reading this?

BTW, not sure if you are changing how device() is called, but if you didn't you can just use 'cisco-nxapi' as the API type (instead of vendor) in the device call.  I'll change mine to 'cisco-onePK' and 'arista-eapi' unless you have other thoughts on that.  So, it looks like r1 = device('r1','cisco-onepk','x.xx.x.').  This would then change how the vendor variable is gathered, but that's an easy one!

**Comment by Mierdin** [comment]
Regarding your first point, I haven't changed anything there. Obviously each function like getCPU() does different stuff since the device API is different, but I left them all in, since this is more about the framework for how CPAL works. Honestly I've been focusing more on filling these functions in for the time being, then will make my module fit properly into your framework.

Regarding your second point, it's probably a good idea to create a few folders - one of which can hold classes like Route/Prefix, Next Hop, etc. Reserved for data that is inherently shared between vendors - all RIBs work much the same way, so normalizing this data into our classes won't be too hard. Might also need a folder for vendor modules, then one for CPAL core proper. I can try this out in my fork if you want and let you know when I'm done so you can see what I mean

**Comment by jedelman8** [comment]
Okay, created some folders for core, vendor modules, and scripts (for general testing, etc.).  Still need to update quite a bit (obviously).   Created a folder for nxapi too.  

I think it makes sense to have standardized data structures like you are saying, but the thing I keep thinking about and the reason this even started was to "think like a user/admin" and not over complicate an API, but simplify it.  I mean, for example, onePK and it seems possibly NX-API has data structures that are complicated and rely on their classes and structure when in reality throwing it in a list or dict is all that's needed.

Even things like next hops.  Are they really needed as their own class or data type?  I'd say no, but they'd be a value and accessible in a routing table dictionary or RIB data type.  

As long as we have the Steve Jobs mentality for usability and "think like users," we'll be okay in the long run! :+1:

**Comment by Mierdin** [comment]
Sure - the only goal would be to ensure that the way you're keeping track of routes or next hops is consistent and easy to use. Traditionally I like to use classes for these so that I can access the data using named properties. 

It's all about making it easier for the tool builders (us) to collect and access data about the network. It is also about making it easier to extend for others that want to contribute. It's easy for others that push code into the project to see the purpose of a class designated for holding route entries - less so for an array or dictionary. The true user wouldn't care which method is used, as long as it works. So in this case, I view the user as future contributors - other tool builders that want to extend and push their own southbound API and desire an easy way to feed routing data back up into the core.

Hope you don't mind my speculation here - I just keep thinking that sometimes a little additional complexity in the short term can mean less complexity over the long term.

**Comment by jedelman8** [comment]
We are on the same page. I'll admit planning for us (tool builders) has been second to me right now. Now that this is expanding a bit, more focus in this area is def a good thing.

**Comment by Mierdin** [comment]
I'll push some of these concepts into my fork and let you know. We'll see at that point if it's worth pursuing. If it's more pain than it's worth, we'll cut it out.

**Comment by yandy-r** [comment]
I'm with Matt on this, extending and modifying a class that holds data-structures is much easier and less prone to breaking the entire thing. Changing a dictionary can cause havoc with a simple typo or forgetting a key:value pair. 

This is what makes python so great IMHO, compared to other languages making models for your data is somewhat "simple". Sure for the non-full-time developer it's not 5 minute work, but still makes it reasonably doable. Looking forward to contributing to the project and getting some headway.

**Comment by jedelman8** [comment]
Sure...feel free to develop some examples of structured classes focused on one API to get started.  We'll see how it comes out.  Or start with parsing args like we spoke about earlier :)  Plenty to do :+1:

**Comment by yandy-r** [comment]
Yup, deff plenty to do, I'll add in the command-line parsing and make sure the right api gets called. We'll go from there, this should be fun.
