### ISSUE TITLE
Arista eaAPI - show hostname 

### ISSUE THREAD

**Issue by jedelman8** [jedelman8/cpal#15]
Yandy

Does this work for you?  I thought it was odd when you changed it to 'show hostname' in the eapi getHostname() methond.  It doesn't work for me...this is why I was parsing through text of another command.

Does this work for you?

```
def getHostname(self):
        output = self.getCmd("show hostname")
        hostname = output[0]['hostname']
        return hostname
```

'show hostname'    isn't even a valid command when at the command prompt on the box.  Not sure what I'm missing.

**Comment by yandy-r** [comment]
yea, it works, maybe it's the version..

```
eos-sw01#sh hostname
Hostname: eos-sw01
FQDN:     eos-sw01.ipyandy.local
```

```
eos-sw01#sh ver
Arista DCS-7050T-64-R
Hardware version:    00.00
Serial number:       JPE13020644
System MAC address:  001c.732e.b558

Software image version: 4.13.2F
Architecture:           i386
Internal build version: 4.13.2F-1649184.4132F.2
Internal build ID:      eeb3c212-b4bd-4c19-ba34-1b0aa36e43f1

Uptime:                 9 hours and 19 minutes
Total memory:           3990500 kB
Free memory:            1291648 kB
```

but it doesn't work on vEOS, probably why, different versions...

**Comment by jedelman8** [comment]
Okay. Was going to say, thought I was losing it. My version doesn't support. All good though.

**Comment by yandy-r** [comment]
The string parsing one wasn't working either, would return "local inf" or something like that. I can create a getHostnameOld() to support the old and new style for now.

what do you think?

**Comment by jedelman8** [comment]
Why don't you get fancy and check OS first so the user doesn't have to know which to call?? :)  If it's 4.12. or earlier, execute getHostnameOld() else getHostname.  Mine is 4.12+ right now.

**Comment by yandy-r** [comment]
not a bad idea, lets see how that plays out.. BOOM!
