### ISSUE TITLE
Using cpal as standalone program

### ISSUE THREAD

**Issue by jedelman8** [jedelman8/cpal#23]
I recently named 'main.py' to 'main' and modified the file permissions to make it an executable.  Original 'main.py is also kept for now as 'main1.py' just in case someone doesn't think this is a good idea.

Output...notice how I am using "./main *args" instead of "python main.py *args"

Trying to improve user experience.

Tested from python shell, and this doesn't seem to affect anything as far as I can tell.  Let me know if you see otherwise.  

```
cisco@onepk:~/apps/cpal/core$ ./main -i 10.1.1.110 -m cisco -f getFacts
{   'connect_ip': '10.1.1.110',
    'cpu_utilization': 11,
    'free_system_memory': 71741952,
    'hostname': 'Router1',
    'interfaces': [   'GigabitEthernet0/3',
                      'GigabitEthernet0/2',
                      'GigabitEthernet0/1',
                      'GigabitEthernet0/0',
                      'GigabitEthernet0/7',
                      'GigabitEthernet0/6',
                      'GigabitEthernet0/5',
                      'GigabitEthernet0/4',
                      'GigabitEthernet0/9',
                      'GigabitEthernet0/8'],
    'last_reboot_reason': 'Unknown reason',
    'platform': 'IOSv',
    'serial_number': '91OSGB4XI9613IB48IJL4',
    'system_uptime': 22737,
    'tags': {   'other': '',
                'pin': 'wan',
                'primary_dept': 'police',
                'region': 'west',
                'site_id': '79'},
    'total_sytem_memory': 134380696,
    'var_name': 'dev',
    'vendor': 'cisco'}
```

**Comment by jedelman8** [comment]
Update:  removing the ".py" extension may not work on windows systems.

**Comment by yandy-r** [comment]
Unfortunately windows is picky with extensions, not just the #! mark. But I think it's usually good practice to leave the extension in. Just mark the main.py executable and should be all good.

**Comment by jedelman8** [comment]
For those wouldn't ever use the python shell, it would be nice to not need
the extension.  Believe me, it could seem confusing.  When I mention
"python" sometimes, eyes roll.  If it's just a script, it could turn into a
smile :)

Thoughts on a shell script calling main.py ?  Just trying to streamline it
and avoid confusion...thoughts?  Worse case, we keep it as main.py for
now...
