### ISSUE TITLE
Use a bit of Inheritance? - Open discussion

### ISSUE THREAD

**Issue by yandy-r** [jedelman8/cpal#5]
One thing I noticed from the code is that, the same methods are defined and implemented for every object. Hear me (or read me out?.. sounds weird) out if you will for a bit. What if we use a bit of inheritance and polymorphism already built into Python?

Create a base parent class, say Switch (example below)

``` python
class Switch(object):
    """docstring for Switch"""
    def __init__(self, args):
        super(Switch, self).__init__()
        self.args = args

    def version(self):
        # generic 
        pass 

    def getCpu(self):
        pass
```

Then all other Vendor specifics inherit from this Parent class. Now I know there will be allot of methods that will have to be re-implemented in the child classes, but not all, any repetitive code that we can cut is a win. 

example:

``` python
class cisco(Switch):
    """docstring for cisco"""
    def __init__(self, arg):
        super(cisco, self).__init__()
        # only specifics to this class, things like IP address, command, user/password
        # can be inherited from Switch class
        self.arg = arg

    # no getVerions()
    # version info for most cisco, arista devices are the same
    # return different data, but that can be abstracter later

    def getCpu(self):
        # cisco specific CPU here
        pass


class arista(Switch):
    """docstring for arista"""
    def __init__(self, arg):
        super(arista, self).__init__()
        # only specifics to this class, things like IP address, command, user/password
        # can be inherited from Switch class
        self.arg = arg

    # no getVerions()
    # version info for most cisco, arista devices are the same
    # return different data, but that can be abstracter later

    def getCpu(self):
        # cisco specific CPU here
        pass
```

Then device() in main will essentially inherit from all vendors, stopping the need to call

``` python
return self.thisDevice.getFunctionNameHere()
```

something like this:

``` python
class device(Switch, arista, cisco, junos):
    """docstring for device"""
    def __init__(self):
        super(device, self).__init__()
        # initialized by Switch parent and passed to the correct child
        # based on 'manufacturer' info

    # no need to create methods to return information
    # only relevant to device() class methods are defined
```

hence, when doing something like:

``` python
sw1 = device(obj, 'cisco', '192.168.1.1')
sw1.getVersion()
```

Using python's built in inheritance and polymorphism, the correct method would be called without the need to re-implement. Code changes in only one place, and no need to look back for specifics.

It's an idea, details can be worked out. Still thinking how to initialize Switch from device() since device is called first. Not even sure it's possible, may need to remove that level, but I'm sure you get the gist. 

Takers? Ideas? It's okay to say I'm crazy or otherwise.

@jedelman8 
@Mierdin 

Thanks

**Comment by jedelman8** [comment]
I'm not sure how many methods would be the same to see these benefits.
 Matt talked about doing something similar with how we structure the data
being returned.  But as for the devices, I'm just not sure b/c each device
essentially has it's own API and it looks like you are implying
getVersion() as an example would be the same across vendors?  What am I
missing?

It's def not ideal how it is today, but main() gives structure for vendor
module builders.  Another idea Kirk had was to make device a function and
not a class. This simplifies it quite a bit such that device wouldn't have
any methods, and would initialize a vendor module/class and return that
back to the user.  However, in doing this, users would see the per vendor
functions when doing something like a dir().  And again, while device()
isn't maybe the most efficient, the plan was to try to call the vendor
function and execute if it exists and return a 'not built yet' or WIP
string, if it wasn't....

Thoughts?

**Comment by yandy-r** [comment]
Yea, I was thinking more in "commands" than API calls, most of the will be different. The idea is simply to create a level of hierarchy and abstraction from the get go. Even if the only thing that Switch class does for now is instantiate variables such as.

```
ip
username
password
functionToCall
manufacturer
```

I understand where you're trying to go with device(), and makes sense, but abstracting it a bit can be of some use as well. Why repeat code if you don't have to?

Having a type of hierarchy would be good for future and still keeps it simple. Either way, I'll work on what I promised for now on my fork. If anything I'll create a different branch say "inheritance" or something and if we dont' like it, can be easily scratched without impacting the "master" or main branch.

**Comment by jedelman8** [comment]
Sounds good, Yandy.  Looking forward to it.
